/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class GerarNota extends javax.swing.JFrame {

    private final double total;
    private final String pagamento;
    private final String descricao;
    
    private final Cliente cliente = null;
    private Cliente clienteSelecionado;
    private List<Cliente> clientes;
    
    private final Usuario usuario;
    /**
     * Creates new form GerarNota
     */
    public GerarNota(double total, String pagamento, String descricao, Cliente clienteSelecionado, Usuario usuario) {
        initComponents();
        
        this.usuario = usuario;
        
        L_nome.setText("Cliente: " + clienteSelecionado.getNome());
        L_telefone.setText("Telefone: " + clienteSelecionado.getTelefone());
        this.descricao = descricao;
        L_descricao.setText("Pedido: "+ descricao);
        
        this.clienteSelecionado = clienteSelecionado;
        L_endereco.setText( "Endereço: " + clienteSelecionado.getRua() + "\n " 
                + clienteSelecionado.getNumero() + "\n "
                + clienteSelecionado.getBairro() + "\n "
                + clienteSelecionado.getCep() );
        
        this.pagamento = pagamento;
        L_pagamento.setText("Pagamento: "+ pagamento);
        this.total = total;
        L_total.setText("Total: "+ total);  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        L_descricao = new javax.swing.JLabel();
        L_total = new javax.swing.JLabel();
        L_pagamento = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        L_telefone = new javax.swing.JLabel();
        L_endereco = new javax.swing.JLabel();
        L_nome = new javax.swing.JLabel();
        btn_gerarNota = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153)));

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(189, 49, 119));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatório do pedido");

        jPanel2.setBackground(new java.awt.Color(255, 210, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        L_descricao.setFont(new java.awt.Font("French Script MT", 1, 29)); // NOI18N
        L_descricao.setForeground(new java.awt.Color(189, 49, 119));
        L_descricao.setText("Pedido: descricao");

        L_total.setFont(new java.awt.Font("French Script MT", 1, 29)); // NOI18N
        L_total.setForeground(new java.awt.Color(189, 49, 119));
        L_total.setText("Total: valor");

        L_pagamento.setFont(new java.awt.Font("French Script MT", 1, 29)); // NOI18N
        L_pagamento.setForeground(new java.awt.Color(189, 49, 119));
        L_pagamento.setText("Pagamento: metodo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L_pagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_pagamento)
                .addGap(18, 18, 18)
                .addComponent(L_total)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 210, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        L_telefone.setFont(new java.awt.Font("French Script MT", 1, 29)); // NOI18N
        L_telefone.setForeground(new java.awt.Color(189, 49, 119));
        L_telefone.setText("Telefone: contato");

        L_endereco.setFont(new java.awt.Font("French Script MT", 1, 29)); // NOI18N
        L_endereco.setForeground(new java.awt.Color(189, 49, 119));
        L_endereco.setText("Endereço: local");

        L_nome.setFont(new java.awt.Font("French Script MT", 1, 29)); // NOI18N
        L_nome.setForeground(new java.awt.Color(189, 49, 119));
        L_nome.setText("Cliente: nome");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_endereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(L_nome)
                .addGap(18, 18, 18)
                .addComponent(L_telefone)
                .addGap(18, 18, 18)
                .addComponent(L_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btn_gerarNota.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        btn_gerarNota.setForeground(new java.awt.Color(189, 49, 119));
        btn_gerarNota.setText("Gerar nota");
        btn_gerarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerarNotaActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        btn_voltar.setForeground(new java.awt.Color(189, 49, 119));
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_gerarNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(550, 550, 550)
                        .addComponent(btn_voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gerarNota)
                    .addComponent(btn_voltar))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gerarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerarNotaActionPerformed
       String nota = "<p> DADOS DA ENTREGA: </p> => Nome do Cliente: " 
                + clienteSelecionado.getNome()
                + "\n => Rua: " + clienteSelecionado.getRua()
                + "\n => Numero: " + clienteSelecionado.getNumero()
                + "\n => Bairro: " + clienteSelecionado.getBairro()
                + "\n => Cep: " + clienteSelecionado.getCep()
                + "\n => Descrição: " + descricao
                + "\n => Pagamento: " + pagamento
                + "\n => Total: " + total;
        
        byte[] buff = nota.getBytes();
        
        try{
                RandomAccessFile raf = new RandomAccessFile("C:\\GravarArquivos\\Venda_"+clienteSelecionado.getNome()+".pdf", "rw");
                raf.write(buff);
                JOptionPane.showMessageDialog(null, "Arquivo gravado", "Conferido", JOptionPane.WARNING_MESSAGE);
                
            }catch(IOException ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro na gravação de arquivo", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_gerarNotaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        Principal principal = new Principal(usuario);
                principal.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_descricao;
    private javax.swing.JLabel L_endereco;
    private javax.swing.JLabel L_nome;
    private javax.swing.JLabel L_pagamento;
    private javax.swing.JLabel L_telefone;
    private javax.swing.JLabel L_total;
    private javax.swing.JButton btn_gerarNota;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
