/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

   private final Usuario user;
    
    /**
     * Creates new form Principal
     */
    public Principal(Usuario user) {
        initComponents();
        
        this.user = user;
        
        L_usuario.setText("Usuário: " + user.getNome());
        L_nivel.setText("Nível: " + user.getNivel());
        
        controlarNivelAcesso();
        
    }
    
    private void controlarNivelAcesso(){
        if(this.user.getNivel().equals("operacional")){
            this.menu_relatorio.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        L_usuario = new javax.swing.JLabel();
        btn_sair = new javax.swing.JToggleButton();
        L_nivel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menu_usuario = new javax.swing.JMenu();
        MI_cadCliente = new javax.swing.JMenuItem();
        menu_relatorio = new javax.swing.JMenu();
        MI_cadProduto = new javax.swing.JMenuItem();
        MI_cadCategoria = new javax.swing.JMenuItem();
        MI_cadFuncionario = new javax.swing.JMenuItem();
        MI_cadUsuario = new javax.swing.JMenuItem();
        menu_venda = new javax.swing.JMenu();
        MI_Venda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/logo_Confeitaria_2.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(189, 49, 119));
        jLabel2.setText("Bem vindo a");

        jLabel3.setFont(new java.awt.Font("Edwardian Script ITC", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(189, 49, 119));
        jLabel3.setText("Confeitaria Barcelle");

        jPanel5.setBackground(new java.awt.Color(255, 210, 244));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/bolin2.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Gabriola", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(189, 49, 119));
        jLabel6.setText("Os melhores bolos do");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(189, 49, 119));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("BRASIL!");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        L_usuario.setFont(new java.awt.Font("Gabriola", 1, 20)); // NOI18N
        L_usuario.setForeground(new java.awt.Color(189, 49, 119));
        L_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_usuario.setText("Usuário: nome");
        L_usuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btn_sair.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        btn_sair.setForeground(new java.awt.Color(189, 49, 119));
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        L_nivel.setFont(new java.awt.Font("Gabriola", 1, 20)); // NOI18N
        L_nivel.setForeground(new java.awt.Color(189, 49, 119));
        L_nivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_nivel.setText("Nível: adm");
        L_nivel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sair)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(L_nivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_sair)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L_usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L_nivel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 720, 390));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/confeitaria-rosa.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 450));

        jMenuBar2.setBackground(new java.awt.Color(255, 210, 244));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar2.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N

        menu_usuario.setForeground(new java.awt.Color(189, 49, 119));
        menu_usuario.setText("Usuario");
        menu_usuario.setFont(new java.awt.Font("Goudy Old Style", 1, 22)); // NOI18N

        MI_cadCliente.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        MI_cadCliente.setForeground(new java.awt.Color(189, 49, 119));
        MI_cadCliente.setText("Clientes");
        MI_cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_cadClienteActionPerformed(evt);
            }
        });
        menu_usuario.add(MI_cadCliente);

        jMenuBar2.add(menu_usuario);

        menu_relatorio.setForeground(new java.awt.Color(189, 49, 119));
        menu_relatorio.setText("Relatório");
        menu_relatorio.setFont(new java.awt.Font("Goudy Old Style", 1, 22)); // NOI18N

        MI_cadProduto.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        MI_cadProduto.setForeground(new java.awt.Color(189, 49, 119));
        MI_cadProduto.setText("Produtos");
        MI_cadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_cadProdutoActionPerformed(evt);
            }
        });
        menu_relatorio.add(MI_cadProduto);

        MI_cadCategoria.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        MI_cadCategoria.setForeground(new java.awt.Color(189, 49, 119));
        MI_cadCategoria.setText("Categorias");
        MI_cadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_cadCategoriaActionPerformed(evt);
            }
        });
        menu_relatorio.add(MI_cadCategoria);

        MI_cadFuncionario.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        MI_cadFuncionario.setForeground(new java.awt.Color(189, 49, 119));
        MI_cadFuncionario.setText("Funcionários");
        MI_cadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_cadFuncionarioActionPerformed(evt);
            }
        });
        menu_relatorio.add(MI_cadFuncionario);

        MI_cadUsuario.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        MI_cadUsuario.setForeground(new java.awt.Color(189, 49, 119));
        MI_cadUsuario.setText("Usuários");
        MI_cadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_cadUsuarioActionPerformed(evt);
            }
        });
        menu_relatorio.add(MI_cadUsuario);

        jMenuBar2.add(menu_relatorio);

        menu_venda.setForeground(new java.awt.Color(189, 49, 119));
        menu_venda.setText("Vendas");
        menu_venda.setFont(new java.awt.Font("Goudy Old Style", 1, 22)); // NOI18N

        MI_Venda.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        MI_Venda.setForeground(new java.awt.Color(189, 49, 119));
        MI_Venda.setText("Comprar Bolos");
        MI_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_VendaActionPerformed(evt);
            }
        });
        menu_venda.add(MI_Venda);

        jMenuBar2.add(menu_venda);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void MI_cadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_cadProdutoActionPerformed
        ProdutoForm produto = new ProdutoForm(user);
                produto.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_MI_cadProdutoActionPerformed

    private void MI_cadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_cadFuncionarioActionPerformed
        FuncionarioForm funcionario = new FuncionarioForm(user);
                funcionario.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_MI_cadFuncionarioActionPerformed

    private void MI_cadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_cadUsuarioActionPerformed
        UsuarioForm usuario = new UsuarioForm();
                usuario.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_MI_cadUsuarioActionPerformed

    private void MI_cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_cadClienteActionPerformed
       ClienteForm cliente = new ClienteForm(user);
                cliente.setVisible(true);
                this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_MI_cadClienteActionPerformed

    private void MI_cadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_cadCategoriaActionPerformed
        CategoriaForm categoria = new CategoriaForm(user);
                categoria.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_MI_cadCategoriaActionPerformed

    private void MI_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_VendaActionPerformed
        VendaBolos venda = new VendaBolos(user);
                venda.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_MI_VendaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_nivel;
    private javax.swing.JLabel L_usuario;
    private javax.swing.JMenuItem MI_Venda;
    private javax.swing.JMenuItem MI_cadCategoria;
    private javax.swing.JMenuItem MI_cadCliente;
    private javax.swing.JMenuItem MI_cadFuncionario;
    private javax.swing.JMenuItem MI_cadProduto;
    private javax.swing.JMenuItem MI_cadUsuario;
    private javax.swing.JToggleButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenu menu_relatorio;
    private javax.swing.JMenu menu_usuario;
    private javax.swing.JMenu menu_venda;
    // End of variables declaration//GEN-END:variables
}
