/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.ClienteDao;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class VendaBolos extends javax.swing.JFrame {

    private final Cliente cliente = null;
    private Cliente clienteSelecionado;
    private List<Cliente> clientes;
    private ClienteDao clienteDao = new ClienteDao();
    
    private final Usuario user;
    
    /**
     * Creates new form Venda
     */
    public VendaBolos(Usuario user) {
        initComponents();
        
        this.user = user;
        
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_doisA = new javax.swing.JRadioButton();
        btn_ouroBranco = new javax.swing.JRadioButton();
        btn_leite = new javax.swing.JRadioButton();
        btn_prestigio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_1kg = new javax.swing.JRadioButton();
        btn_2kg = new javax.swing.JRadioButton();
        btn_2kge5 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        check_topo = new javax.swing.JCheckBox();
        check_confetes = new javax.swing.JCheckBox();
        check_lascas = new javax.swing.JCheckBox();
        check_brigadeiros = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cb_pagamento = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        txf_pesquisa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_pesquisa = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btn_fecharPedido = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153)));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/logo_Confeitaria_2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jPanel2.setBackground(new java.awt.Color(255, 210, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_doisA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_doisA.setText("Dois Amores.......................................");
        btn_doisA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doisAActionPerformed(evt);
            }
        });

        btn_ouroBranco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_ouroBranco.setText("Ouro Branco.......................................");
        btn_ouroBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ouroBrancoActionPerformed(evt);
            }
        });

        btn_leite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_leite.setText("Leite ninho c/ morango.................");
        btn_leite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_leiteActionPerformed(evt);
            }
        });

        btn_prestigio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_prestigio.setText("Pretígio..................................................");
        btn_prestigio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prestigioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("R$ 53,00");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("R$ 55,00");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("R$ 58,00");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("R$ 53,00");

        jLabel2.setText("Valor do Kg");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_doisA, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_prestigio, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_ouroBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_leite, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_doisA))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ouroBranco)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_leite)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_prestigio)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel10.setFont(new java.awt.Font("Edwardian Script ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(189, 49, 119));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Confeitaria Barcelle");

        jPanel3.setBackground(new java.awt.Color(255, 210, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Edwardian Script ITC", 1, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(189, 49, 119));
        jLabel5.setText("Quantidade");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setText("mínimo 1,5Kg");

        buttonGroup1.add(btn_1kg);
        btn_1kg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_1kg.setText("1,5 KG");
        btn_1kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1kgActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_2kg);
        btn_2kg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_2kg.setText("2 KG");
        btn_2kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2kgActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_2kge5);
        btn_2kge5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_2kge5.setText("2,5 KG");
        btn_2kge5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2kge5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_1kg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_2kg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_2kge5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_1kg)
                .addGap(18, 18, 18)
                .addComponent(btn_2kg)
                .addGap(18, 18, 18)
                .addComponent(btn_2kge5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 210, 244));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Edwardian Script ITC", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(189, 49, 119));
        jLabel3.setText("Decoração");

        check_topo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        check_topo.setText("Topo de bolo personalizado (R$ 20,00)");

        check_confetes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        check_confetes.setText("Kit Kat e Confetes (R$ 10,00)");

        check_lascas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        check_lascas.setText("Lascas de Chocolate (R$ 10,00)");

        check_brigadeiros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        check_brigadeiros.setText("Brigadeiros (R$ 10,00)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_topo)
                    .addComponent(check_confetes)
                    .addComponent(check_lascas)
                    .addComponent(check_brigadeiros)
                    .addComponent(jLabel3)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_topo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_confetes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_lascas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_brigadeiros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 210, 244));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("French Script MT", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(189, 49, 119));
        jLabel11.setText("Forma de Pagamento");

        cb_pagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crédito", "Débito", "Boleto", "Pix" }));
        cb_pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(cb_pagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 210, 244));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_pesquisaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("French Script MT", 1, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(189, 49, 119));
        jLabel12.setText("Selecione seu cadastro");

        jLabel13.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(189, 49, 119));
        jLabel13.setText("Não possui cadastro?");

        btn_pesquisa.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        btn_pesquisa.setForeground(new java.awt.Color(189, 49, 119));
        btn_pesquisa.setText("Pesquisar");
        btn_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisaActionPerformed(evt);
            }
        });

        btn_cadastrar.setFont(new java.awt.Font("French Script MT", 1, 18)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(189, 49, 119));
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel12)
                        .addGap(8, 8, 8)
                        .addComponent(txf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_pesquisa)))
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(btn_cadastrar))
                .addContainerGap())
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "telefone", "rua", "numero", "bairro", "cep"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        btn_fecharPedido.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        btn_fecharPedido.setForeground(new java.awt.Color(189, 49, 119));
        btn_fecharPedido.setText("Fechar Pedido");
        btn_fecharPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharPedidoActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        btn_voltar.setForeground(new java.awt.Color(189, 49, 119));
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_fecharPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_voltar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_fecharPedido)
                            .addComponent(btn_voltar))))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_leiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_leiteActionPerformed
        if(btn_leite.isSelected()){
            btn_ouroBranco.setSelected(false);
            btn_doisA.setSelected(false);
            btn_prestigio.setSelected(false);
        }
    }//GEN-LAST:event_btn_leiteActionPerformed

    private void btn_doisAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doisAActionPerformed
        if(btn_doisA.isSelected()){
            btn_ouroBranco.setSelected(false);
            btn_leite.setSelected(false);
            btn_prestigio.setSelected(false);
        }
    }//GEN-LAST:event_btn_doisAActionPerformed

    private void btn_1kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1kgActionPerformed
        if(btn_1kg.isSelected()){
            btn_2kg.setSelected(false);
            btn_2kge5.setSelected(false);
        }
    }//GEN-LAST:event_btn_1kgActionPerformed

    private void btn_2kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2kgActionPerformed
        if(btn_2kg.isSelected()){
            btn_1kg.setSelected(false);
            btn_2kge5.setSelected(false);
        }
    }//GEN-LAST:event_btn_2kgActionPerformed

    private void btn_2kge5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2kge5ActionPerformed
        if(btn_2kge5.isSelected()){
            btn_1kg.setSelected(false);
            btn_2kg.setSelected(false);
        }
    }//GEN-LAST:event_btn_2kge5ActionPerformed

    private void cb_pagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pagamentoActionPerformed
        
    }//GEN-LAST:event_cb_pagamentoActionPerformed

    private void btn_ouroBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ouroBrancoActionPerformed
        if(btn_ouroBranco.isSelected()){
            btn_doisA.setSelected(false);
            btn_leite.setSelected(false);
            btn_prestigio.setSelected(false);
        }
    }//GEN-LAST:event_btn_ouroBrancoActionPerformed

    private void btn_prestigioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prestigioActionPerformed
        if(btn_prestigio.isSelected()){
            btn_doisA.setSelected(false);
            btn_leite.setSelected(false);
            btn_ouroBranco.setSelected(false);
        }
    }//GEN-LAST:event_btn_prestigioActionPerformed

    private void txf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_pesquisaActionPerformed

    private void btn_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisaActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_btn_pesquisaActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        ClienteForm cliente = new ClienteForm(user);
                cliente.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_fecharPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharPedidoActionPerformed
       
        //REGISTRAR O CLIENTE (NOME, TELEFONE,ENDEREÇO)
        int linha = tabela.getSelectedRow();
         if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
         clienteSelecionado = clientes.get(linha);
         
        //REGISTRAR O MÉTODO DE PAGAMENTO
        String pagamento = "";
        if(cb_pagamento == null){
            JOptionPane.showMessageDialog(null, "Selecione o método de pagamento", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else{
            if(cb_pagamento.getSelectedItem().equals("Crédito")){
            pagamento = "Crédito";
        }else if(cb_pagamento.getSelectedItem().equals("Débito")){
            pagamento = "Débito";
        }else if(cb_pagamento.getSelectedItem().equals("Boleto")){
            pagamento = "Boleto";
        }else if(cb_pagamento.getSelectedItem().equals("Pix")){
            pagamento = "Pix";
        }
        }
        
        //REGISTRANDO ESCOLHAS, CALCULANDO E REGISTRANDO O VALOR TOTAL
        String bolo = " ";
        String kilos = "";
        String topo = " Topo personalizado R$ 20,00 ";
        String confetes = " Adicional de confete e kit-kat R$ 10,00 ";
        String lascas = " Adicional de lascas de chocolate R$ 10,00 ";
        String brigadeiros = " Adicional de brigadeiro R$ 10,00 ";
        
        double total = 0;
        if(btn_doisA.isSelected()){
            total = total + 53.00;
            bolo = " Dois Amores R$ 53,00 ";
        }else if (btn_ouroBranco.isSelected()){
            total = total + 55.00;
            bolo = " Ouro Branco R$ 55,00 ";
        }else if(btn_leite.isSelected()){
            total = total + 58.00;
            bolo = " Leite Ninho R$ 58,00 ";
        }else if(btn_prestigio.isSelected()){
            total = total + 53.00 ;
            bolo = " Prestígio R$ 58,00 ";
        }
        if(btn_1kg.isSelected()){
            total = total * 1;
            kilos = " Peso de 1 Kg ";
        }else if(btn_2kg.isSelected()){
            total = total * 2;
            kilos = " Peso de 2 Kg ";
        }else if(btn_2kge5.isSelected()){
            total = total * 2.5;
            kilos = " Peso de 2,5 Kg ";
        }
        
        String extra = "";
        if(check_topo.isSelected()){
            total = total + 20.00;
            extra = topo;
        }
        if(check_confetes.isSelected()){
            total = total + 10.00;
            extra = confetes;
        }
        if(check_lascas.isSelected()){
            total = total + 10.00;
            extra = lascas;
        }
        if(check_brigadeiros.isSelected()){
            total = total + 10.00;
            extra = brigadeiros;
        }
        
        String descricao = "" + bolo + "" + kilos + "" + extra + "";

        GerarNota nota = new GerarNota(total, pagamento, descricao, clienteSelecionado, user);
                nota.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btn_fecharPedidoActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        Principal principal = new Principal( user);
                principal.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void atualizarTabela() {
        try {
            clientes = clienteDao.buscarPeloNome(txf_pesquisa.getText());

            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.setNumRows(0);
            for (int i = 0; i < clientes.size(); i++) {
                Cliente cliente = clientes.get(i);
                model.addRow(new Object[]{cliente.getNome(), cliente.getCpf(), cliente.getTelefone(), cliente.getRua(), cliente.getNumero(), cliente.getBairro(), cliente.getCep(),});
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_1kg;
    private javax.swing.JRadioButton btn_2kg;
    private javax.swing.JRadioButton btn_2kge5;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JRadioButton btn_doisA;
    private javax.swing.JButton btn_fecharPedido;
    private javax.swing.JRadioButton btn_leite;
    private javax.swing.JRadioButton btn_ouroBranco;
    private javax.swing.JButton btn_pesquisa;
    private javax.swing.JRadioButton btn_prestigio;
    private javax.swing.JButton btn_voltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_pagamento;
    private javax.swing.JCheckBox check_brigadeiros;
    private javax.swing.JCheckBox check_confetes;
    private javax.swing.JCheckBox check_lascas;
    private javax.swing.JCheckBox check_topo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txf_pesquisa;
    // End of variables declaration//GEN-END:variables
}
